name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  workshop-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to Steam Workshop
        uses: Earu/GSW-action@V3.1.12
        with:
          account-name: ${{secrets.STEAM_NAME}}
          account-password: ${{secrets.STEAM_PASSWORD}}
          workshop-id: '2807801954'
          addon-path: ${{env.GITHUB_WORKSPACE}}